// NFT Floor Price Card Component
// Generated by [N]skills

'use client';

import { useNFTFloor } from '@/hooks/useNFTFloor';

interface NFTFloorCardProps {
  collectionAddress: string;
  blockchain?: string;
  className?: string;
}

export function NFTFloorCard({ collectionAddress, blockchain, className }: NFTFloorCardProps) {
  const { data: floor, isLoading, error } = useNFTFloor({ collectionAddress, blockchain });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 animate-pulse ${className}`}>
        <div className="h-4 bg-zinc-700 rounded w-1/3 mb-2" />
        <div className="h-8 bg-zinc-700 rounded w-1/2" />
      </div>
    );
  }

  if (error || !floor) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load floor price</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <h3 className="text-sm font-medium text-zinc-400 mb-2">Floor Price</h3>
      <p className="text-2xl font-bold text-white">
        {floor.floor_price_eth.toFixed(4)} ETH
      </p>
      <p className="text-sm text-zinc-500">
        ${floor.floor_price_usd.toLocaleString()}
      </p>
      <div className="mt-3 pt-3 border-t border-zinc-700/50 grid grid-cols-2 gap-4 text-xs">
        <div>
          <p className="text-zinc-500">24h Volume</p>
          <p className="text-zinc-300">${floor.volume_24h.toLocaleString()}</p>
        </div>
        <div>
          <p className="text-zinc-500">24h Sales</p>
          <p className="text-zinc-300">{floor.sales_count_24h}</p>
        </div>
      </div>
    </div>
  );
}

export default NFTFloorCard;