// NFT Floor Price Hook
// Generated by [N]skills

'use client';

import { useQuery } from '@tanstack/react-query';
import { duneClient, type NFTFloorData } from '@/lib/dune-client';

export interface UseNFTFloorParams {
  collectionAddress: string;
  blockchain?: string;
  enabled?: boolean;
}

export function useNFTFloor(params: UseNFTFloorParams) {
  return useQuery({
    queryKey: ['dune-nft-floor', params.collectionAddress, params.blockchain],
    queryFn: () => duneClient.getNFTFloor(
      params.collectionAddress,
      params.blockchain ?? 'ethereum'
    ),
    enabled: !!params.collectionAddress && (params.enabled ?? true),
    staleTime: 300000,
  });
}